### PR TITLE
feat(main): add lv_demos_create, now support running demos with argument(widgets, music, benchmark...)

### PR DESCRIPTION
**Pull request by bjsylvia**
If use cmake, now you can start demo with command list:
`../bin/main music` or  `../bin/main benchmark` or `../bin/main` for default widgets.

### CODE REVIEW

**Comment by kisvegabor** [comment]
What if I'm using Eclipse manged build and I just want to start a demo?

**Comment by bjsylvia** [comment]
> What if I'm using Eclipse manged build and I just want to start a demo?

We can configure it by `Run configurations`->`Arguments`->`Program arguments`.

image

**Comment by kisvegabor** [comment]
What about something like 
```c
#ifndef CMAKE
lv_demo_widgets();
#else
//Some comments to tell what's going on
your code
#endif
```

**Comment by bjsylvia** [comment]
> What about something like
> 
> ```c
> #ifndef CMAKE
> lv_demo_widgets();
> #else
> //Some comments to tell what's going on
> your code
> #endif
> ```

Using Eclipse, the default running is the widgets demo, which has the same effect as the code above, but it also supports switching to other demos through `Run configurations` without recompiling. Do you agree?

**Comment by kisvegabor** [comment]
My goal is to provide the simplest "first look experience" for the users.

What about
```
if(argc == 0) {
   lv_demo_widgets();
} else {
   your code
}
```

**Comment by kisvegabor** [comment]
Great!

**Pull request merged**
