### PR TITLE
cmake: use c99 instead

### PR DESCRIPTION
**Pull request by XuNeo**

### CODE REVIEW

**Comment by XuNeo** [comment]
Note that even specifies to use `99`, gcc uses gnu99 instead.
And even with -std=c99, for clang anonymous union still doesn't report error.

**Comment by kisvegabor** [comment]
I've just found this: https://stackoverflow.com/a/3228172

**Comment by XuNeo** [comment]
> I've just found this: https://stackoverflow.com/a/3228172

True, `gnu99` also supports `anonymous union`.  Do you want me to update cmake to use `-std=c99` strictly?

**Comment by kisvegabor** [comment]
So even C99 is not enough for anonymous unions but we need to move to C11. Do you see any other advantages of updating to C11?

**Comment by XuNeo** [comment]
Let's use c99 for now until we have final decision.

The issue here is even updating `CMakeLists.txt` to say use `99` version, it does not mean `c99`. For GCC, it's actually `gnu99` used.
Also for `clang`, even specifying `-std=c99`, it also cannot report error in current upstream code where `anonymous  union` is used.

**Comment by kisvegabor** [comment]
> Let's use c99 for now until we have final decision.

I agree, it's sill better than C11.

**Pull request merged**
